### PR TITLE
feat(unclaim): support unclaim on owner

### PR DESCRIPTION
**Pull request by daddykotex**
The commits' message say it all

### CODE REVIEW

**Comment by daddykotex** [comment]
@mvonthron

**Comment by daddykotex** [comment]
The build fail on a specific version, I'll investigate. It seems related to the mock

**Comment by daddykotex** [comment]
It's not even test that I updated... @mvonthron got a clue?

**Comment by daddykotex** [comment]
Looking at the build history, previous merge was also failing:
https://travis-ci.org/mnubo/smartobjects-net-client/builds

**Comment by mvonthron** [comment]
We almost always had the "latest" failing whereas "4.4.2" passed...
although "latest" was actually 4.4.2. I don't know why, maybe a parallel
build issue. We usually restarted the failing build and it always passed
the second time.

**Comment by daddykotex** [comment]
worked!

**Pull request merged**
