### PR TITLE
chore(publishing): change publishing to .sh file to respect Travis requirement

### PR DESCRIPTION
**Pull request by jonathanhallee**
Since previous deploy failed.

Also adjusted paths in the deploy script. They were based on my local test but travis is executing from the root of the repo

See: https://docs.travis-ci.com/user/deployment/script/

### CODE REVIEW

**Comment by daddykotex** [comment]
can you change the url to the travis badge in the README (while you're at it)

**Comment by daddykotex** [comment]
also, I'm not sure I understand how it fixes the issue, but like with every CI out there, it's a shot in the dark to know whether you actually do something

**Comment by jtheoof** [comment]
I concur with @daddykotex not sure how that can fix anything. But CI is :heart:

**Comment by jonathanhallee** [comment]
> I concur with @daddykotex not sure how that can fix anything. But CI is ❤️

Yeah, I dont see any other than just..... trying :/

**Comment by jonathanhallee** [comment]
> also, I'm not sure I understand how it fixes the issue, but like with every CI out there, it's a shot in the dark to know whether you actually do something

Well, @daddykotex the deploy didnt work because the script didn't allow an array of scripts to be passed, it's their example to deploy using a .sh deploy script

**Comment by daddykotex** [comment]
Ok, I assumed `script` was an array like with GitLab CI

**Comment by jonathanhallee** [comment]
> Ok, I assumed `script` was an array like with GitLab CI

I assumed as well hahaha

**Comment by daddykotex** [comment]
crap:

https://travis-ci.com/github/mnubo/smartobjects-net-client/builds/217504789

**Comment by jonathanhallee** [comment]
> crap:
> 
> https://travis-ci.com/github/mnubo/smartobjects-net-client/builds/217504789

On it. It's progress :D

**Pull request merged**
