### PR TITLE
Timezone support in registration date of Owner and SmartObject

### PR DESCRIPTION
**Pull request by daddykotex**

### CODE REVIEW

**Comment by daddykotex** [comment]
Only the last commit is relevant. See issue MM-7121

**Comment by dmasse76** [comment]
Minor comment, otherwise looks good.

**Comment by daddykotex** [comment]
Do not merge yet, I'm trying to figure out why travis fails.

**Comment by daddykotex** [comment]
When I test locally, everything is good but on travis, some tests that expect some classes of exception receives other types of exceptions instead.

**Pull request merged**
