### PR TITLE
Exponential Backoff with Polly

### PR DESCRIPTION
**Pull request by daddykotex**
Using https://github.com/App-vNext/Polly, the SDK now supports exponential backoff.

### CODE REVIEW

**Comment by mvonthron** [comment]
What required this change?

**Comment by daddykotex** [comment]
Sometimes we will have to do maintenance, when this happen the service will return a 503 Service Unavailable. We want or client to retry when this happens.

David Lemieux suggested this and we're doing it for all the SDKs

**Comment by jtheoof** [comment]
One test has failed.

**Comment by daddykotex** [comment]
`git commit --amend --no-edit && git push origin backoff -f`

**Comment by daddykotex** [comment]
My bad, I dropped one commit -_-

**Pull request merged**
